baseURL = "http://examplesite.org"
disableLanguages = []
disqusShortname = ""
paginate = "4"
summaryLength = "30"
theme = "airspace-hugo"
themesDir = "../.."
title = "Future in our Hands Sierra Leone"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2020 Future in Our Hands All Rights Reserved - [Developed By: Link Corporation Limited SL](https://linkcorp-sl.com) "
languageCode = "en-us"
languageName = "En"
weight = 1
[[Languages.en.menu.footer]]
URL = "about"
name = "About"
weight = 1
[[Languages.en.menu.footer]]
URL = "project"
name = "Project"
weight = 2
[[Languages.en.menu.footer]]
URL = "service"
name = "Structure"
weight = 3
[[Languages.en.menu.footer]]
URL = "contact"
name = "Contact"
weight = 6
[[Languages.en.menu.main]]
URL = "blog"
name = "POST"
weight = "5"
[[Languages.en.menu.main]]
URL = "/"
name = "Home"
weight = 1
[[Languages.en.menu.main]]
URL = "about"
name = "About"
weight = 2
[[Languages.en.menu.main]]
URL = "project"
name = "Project"
weight = 3
[[Languages.en.menu.main]]
URL = "blog"
name = "Latest Post"
weight = 4
[[Languages.en.menu.main]]
URL = "service"
hasChildren = true
name = "Structure"
weight = 5
[[Languages.en.menu.main]]
URL = "contact"
name = "Contact"
weight = 6
[Languages.fr]
contentDir = "content/french"
copyright = "Copyright &copy; 2020 [Themefisher](https://themefisher.com) All Rights Reserved"
languageCode = "fr-fr"
languageName = "Fr"
weight = 2
[[Languages.fr.menu.footer]]
URL = "about"
name = "About"
weight = 1
[[Languages.fr.menu.footer]]
URL = "project"
name = "Project"
weight = 2
[[Languages.fr.menu.footer]]
URL = "service"
name = "Service"
weight = 3
[[Languages.fr.menu.footer]]
URL = "pricing"
name = "Pricing"
weight = 4
[[Languages.fr.menu.footer]]
URL = "faq"
name = "FAQ"
weight = 5
[[Languages.fr.menu.footer]]
URL = "contact"
name = "Contact"
weight = 6
[[Languages.fr.menu.main]]
URL = "/"
name = "Accueil"
weight = 1
[[Languages.fr.menu.main]]
URL = "about"
name = "À propos"
weight = 2
[[Languages.fr.menu.main]]
URL = "project"
name = "Projet"
weight = 3
[[Languages.fr.menu.main]]
URL = "blog"
name = "Blog"
weight = 4
[[Languages.fr.menu.main]]
hasChildren = true
name = "Pages"
weight = 5
[[Languages.fr.menu.main]]
URL = "faq"
name = "FAQ"
parent = "Pages"
[[Languages.fr.menu.main]]
URL = "pricing"
name = "Tarification"
parent = "Pages"
[[Languages.fr.menu.main]]
URL = "service"
name = "Un service"
parent = "Pages"
[[Languages.fr.menu.main]]
URL = "contact"
name = "Contact"
weight = 6
[markup.goldmark.renderer]
unsafe = true
[outputs]
home = ["HTML"]
[params]
author = "Edmond Kposowa "
contact_form_action = "#"
description = "The Future In Our Hands-Sierra Leone (FIOH-SL) "
email = "fiohsl2018@gmail.com "
google_analitycs_id = ""
location = "20 Lunsar Road, Makeni "
logo = "/images/fioh-logo.PNG"
logo_width = "85px"
mobile = "+232 78 392-874/ 80 101-714 "
multi_author = false
[params.cookies]
enable = true
expire_days = 2
[params.gmap]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[params.nav_button]
enable = true
label = "Get A Quote"
link = "contact"
[[params.plugins.css]]
attributes = "media='screen'"
link = "plugins/bootstrap/bootstrap.min.css"
page = "/"
[[params.plugins.css]]
attributes = ""
link = "plugins/Ionicons/css/ionicons.min.css"
page = "/"
[[params.plugins.css]]
attributes = ""
link = "plugins/magnific-popup/magnific-popup.min.css"
page = "/"
[[params.plugins.css]]
attributes = ""
link = "plugins/slick/slick.css"
page = "/"
[[params.plugins.js]]
attributes = ""
link = "plugins/jQuery/jquery.min.js"
page = "/"
[[params.plugins.js]]
attributes = ""
link = "plugins/bootstrap/bootstrap.min.js"
page = "/"
[[params.plugins.js]]
attributes = ""
link = "plugins/slick/slick.min.js"
page = "/"
[[params.plugins.js]]
attributes = ""
link = "plugins/magnific-popup/magnific-popup.min.js"
page = "/"
[[params.plugins.js]]
attributes = ""
link = "plugins/shuffle/shuffle.min.js"
page = "/"
[[params.plugins.js]]
attributes = ""
link = "plugins/google-map/gmap.js"
page = "contact/"
[params.preloader]
enable = true
preloader = ""
[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]
[[params.social]]
icon = "ion-social-googleplus-outline"
link = "#"
[[params.social]]
icon = "ion-social-linkedin-outline"
link = "#"
[[params.social]]
icon = "ion-social-pinterest-outline"
link = "#"
[[params.social]]
icon = "ion-social-dribbble-outline"
link = "#"
[[params.social]]
icon = "ion-social-twitter-outline"
link = "#"
[[params.social]]
icon = "ion-social-facebook-outline"
link = "#"
