---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: text
  name: description
  label: description
  description: this is meta description
- type: file
  name: image
  label: image
- type: file
  name: bg_image
  label: bg image
  description: page header background image
- type: text
  name: category
  label: category
  description: Filter Category
- type: field_group_list
  name: information
  label: information
  fields:
  - type: text
    name: label
    label: label
  - type: text
    name: info
    label: info
pages:
- exampleSite/content/english/project/Current.md
- exampleSite/content/english/project/Current.md
- exampleSite/content/english/project/Past.md
- exampleSite/content/english/project/agriculture-food-security.md
- exampleSite/content/english/project/community-asset-rehabilitation.md
- exampleSite/content/english/project/community-asset-rehabilitation.md
- exampleSite/content/english/project/community-re-integration-and-resettlement..md
- exampleSite/content/english/project/conservation-agriculture-project-1.md
- exampleSite/content/english/project/conservation-agriculture-project.md
- exampleSite/content/english/project/food-for-work-ffw-1.md
- exampleSite/content/english/project/food-for-work-ffw.md
- exampleSite/content/english/project/inland-valley-swamp-development.md
- exampleSite/content/english/project/inland-valley-swamp-development.md
- exampleSite/content/english/project/lead.md
- exampleSite/content/english/project/life-skills-training-for-youths-1.md
- exampleSite/content/english/project/life-skills-training-for-youths.md
- exampleSite/content/english/project/livelihood-enhancement-asset-dev.project-1.md
- exampleSite/content/english/project/livelihood-enhancement-asset-dev.project.md
- exampleSite/content/english/project/micro-finance-1.md
- exampleSite/content/english/project/micro-finance.md
- exampleSite/content/english/project/past.md
- exampleSite/content/english/project/runlip.md
- exampleSite/content/english/project/runlip.md
- exampleSite/content/english/project/tonkolili-education-livelihood-project-telp.md
- exampleSite/content/english/project/un-bombali-youth-employment-project-1.md
- exampleSite/content/english/project/un-bombali-youth-employment-project.md
- exampleSite/content/english/project/village-child-education.md
- exampleSite/content/english/project/village-child-education.md
- exampleSite/content/english/project/village-savings-loans-vs-l-1.md
- exampleSite/content/english/project/village-savings-loans-vs-l.md
